APPLICATION ?= thread-shell

BOARD ?= native

# Add extra modules here
USEMODULE += shell
USEMODULE += shell_cmds_default
USEMODULE += ps
USEMODULE += ztimer
USEMODULE += ztimer_msec


# Add extended thread information
DEVELHELP ?= 1

RIOTBASE ?= $(CURDIR)/../../RIOT

include $(RIOTBASE)/Makefile.include
